import frappe


UPDATE_EXISTING = True


SYNTHETIC = {
    "tenant": "TEST-NEXUS",
    "business_unit": "Nexus Synthetic BU",
    "other_business_unit": "Other Synthetic BU",
    "project": "Alpha Orbit Project",
    "other_project": "Beta Orbit Project",
    "context": "Synthetic ERP",
    "sub_context": "Orbit Operations",
    "entity_type": "Synthetic Product",
    "entity": "Nexus Test Orbit",
    "overview_topic": "Orbit Overview",
    "valuation_topic": "Orbit Valuation Protocol",
    "missing_topic": "Orbit Missing Topic",
    "unrelated_topic": "Orbit Unrelated Topic",
    "draft_topic": "Orbit Draft Topic",
    "disabled_topic": "Orbit Disabled Topic",
    "deny_topic": "Orbit Deny Priority",
    "missing_embedding_topic": "Orbit Missing Embedding",
}


def execute():
    test_cases = [
        # ------------------------------------------------------------
        # PUBLIC / WEBSITE / RESPONSE MODE
        # ------------------------------------------------------------
        {
            "name": "PUBLIC-OVERVIEW-TEST",
            "test_title": "Public Overview Test",
            "short_description": "Guest asks public synthetic orbit overview question.",
            "test_category": "Public Knowledge",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WEBSITE-PUBLIC-QA-TEST",
            "test_title": "Website Public Q&A Test",
            "short_description": "Website visitor asks public synthetic orbit Q&A question.",
            "test_category": "Public Knowledge",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "Can you explain Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "caller_system": "Website Q&A",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WEBSITE-CHAT-PUBLIC-TEST",
            "test_title": "Website Chat Public Test",
            "short_description": "Website chatbot answers a public synthetic orbit question.",
            "test_category": "Response Behaviour",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "Hi, what is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "chat",
            "caller_system": "Website Chat",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "CHAT-RESPONSE-MODE-TEST",
            "test_title": "Chat Response Mode Test",
            "short_description": "Validates chatbot response behavior using approved synthetic knowledge.",
            "test_category": "Response Behaviour",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "chat",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "QA-RESPONSE-MODE-TEST",
            "test_title": "Q&A Response Mode Test",
            "short_description": "Validates formal Q&A response behavior using approved synthetic knowledge.",
            "test_category": "Response Behaviour",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "TOP-K-LIMIT-TEST",
            "test_title": "Top K Limit Test",
            "short_description": "Limits retrieval to one source when top_k is 1.",
            "test_category": "Response Behaviour",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 1,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },

        # ------------------------------------------------------------
        # ACCESS CONTROL
        # ------------------------------------------------------------
        {
            "name": "RESTRICTED-DENIAL-TEST",
            "test_title": "Restricted Access Denial Test",
            "short_description": "Viewer role should not access restricted orbit valuation knowledge.",
            "test_category": "Access Control",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Viewer",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "FINANCE-ALLOWED-TEST",
            "test_title": "Finance Allowed Test",
            "short_description": "Orbit Analyst accesses restricted synthetic valuation knowledge.",
            "test_category": "Access Control",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "RESTRICTED-CHUNK-STABILITY-TEST",
            "test_title": "Restricted Chunk Stability Test",
            "short_description": "Restricted chunks must remain excluded during stable retrieval scoring.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Viewer",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "DENIED-CHUNK-NOT-SELECTED-TEST",
            "test_title": "Denied Chunk Not Selected Test",
            "short_description": "Validates that denied restricted chunks are not selected in final retrieval results.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Viewer",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "DENY-OVER-ALLOW-PRECEDENCE-TEST",
            "test_title": "Deny Over Allow Precedence Test",
            "short_description": "If a role is both allowed and denied, denial must win.",
            "test_category": "Access Control",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["deny_topic"],
            "query": "Explain orbit deny priority rule",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "MULTI-ROLE-ALLOWED-TEST",
            "test_title": "Multi Role Allowed Test",
            "short_description": "User with multiple roles should access knowledge if one role is allowed.",
            "test_category": "Access Control",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Viewer,Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },

        # ------------------------------------------------------------
        # PROJECT SCOPE
        # ------------------------------------------------------------
        {
            "name": "PROJECT-WITH-GENERAL-TEST",
            "test_title": "Project + General Test",
            "short_description": "Project query allows project-specific knowledge and general fallback without leaking unrelated project knowledge.",
            "test_category": "Project Scope",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "with_general",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "STRICT-PROJECT-TEST",
            "test_title": "Strict Project Test",
            "short_description": "Project query retrieves only project-specific knowledge.",
            "test_category": "Project Scope",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "strict",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Project Alpha Override",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "OTHER-PROJECT-STRICT-LEAKAGE-TEST",
            "test_title": "Other Project Leakage - Strict",
            "short_description": "Strict project mode should not retrieve another project's knowledge.",
            "test_category": "Project Scope",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["other_project"],
            "project_scope_mode": "strict",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "STRICT-PROJECT-NO-GENERAL-LEAKAGE-TEST",
            "test_title": "Strict Project No General Leakage",
            "short_description": "Strict project mode must not retrieve general fallback chunks.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "strict",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Project Alpha Override",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WITH-GENERAL-PROJECT-BALANCE-TEST",
            "test_title": "With General Project Balance Test",
            "short_description": "Project with general mode should balance project and general retrieval safely.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "with_general",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Alpha Orbit Project Nexus Test Orbit valuation rules",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Project Alpha Override",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "PROJECT-PREFERRED-OVER-GENERAL-TEST",
            "test_title": "Project Preferred Over General Test",
            "short_description": "With general mode should still retrieve project-specific valuation knowledge.",
            "test_category": "Project Scope",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "with_general",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Alpha Orbit Project valuation rules",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Project Alpha Override",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },

        # ------------------------------------------------------------
        # FALLBACK / ISOLATION
        # ------------------------------------------------------------
        {
            "name": "NO-CONTEXT-FALLBACK-TEST",
            "test_title": "No Context Fallback Test",
            "short_description": "Unknown topic should trigger the safe fallback answer.",
            "test_category": "Fallback",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["missing_topic"],
            "query": "Unknown synthetic orbit question",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "WEBSITE-NO-CONTEXT-FALLBACK-TEST",
            "test_title": "Website No Context Fallback Test",
            "short_description": "Website visitor unknown question should return safe fallback.",
            "test_category": "Public Knowledge",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["missing_topic"],
            "query": "Can you explain an unknown orbit module?",
            "top_k": 5,
            "use_case": "qa",
            "caller_system": "Website Q&A",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "BUSINESS-UNIT-ISOLATION-TEST",
            "test_title": "Business Unit Isolation Test",
            "short_description": "Wrong Business Unit should not leak synthetic orbit knowledge.",
            "test_category": "Business Unit Scope",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["other_business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "TENANT-ISOLATION-TEST",
            "test_title": "Tenant Isolation Test",
            "short_description": "Wrong tenant should not retrieve TEST-NEXUS synthetic knowledge.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS-ALT",
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "WEAK-RETRIEVAL-STABILITY-TEST",
            "test_title": "Weak Retrieval Stability Test",
            "short_description": "Validates that weak retrieval does not produce an unsafe answer when confidence is low.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "with_general",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["unrelated_topic"],
            "query": "Explain something that is not available in the approved synthetic orbit knowledge.",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },

        # ------------------------------------------------------------
        # GOVERNANCE / STABILITY / DEBUG
        # ------------------------------------------------------------
        {
            "name": "RETRIEVAL-STABILITY-SCORE-TEST",
            "test_title": "Retrieval Stability Score Test",
            "short_description": "Validates retrieval stability scoring visibility for grounded retrieval.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "RERANK-STABILITY-DEBUG-TEST",
            "test_title": "Rerank Stability Debug Test",
            "short_description": "Validates reranking and retrieval debug visibility.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "Nexus Test Orbit valuation handling Blue Radius Index",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "MULTI-QUERY-STABILITY-TEST",
            "test_title": "Multi Query Stability Test",
            "short_description": "Validates that multi-query retrieval consistently retrieves synthetic orbit valuation knowledge.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "project": SYNTHETIC["project"],
            "project_scope_mode": "with_general",
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["valuation_topic"],
            "query": "How is Nexus Test Orbit valuation calculated?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Blue Radius Index",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "DRAFT-KNOWLEDGE-NOT-RETRIEVED-TEST",
            "test_title": "Draft Knowledge Not Retrieved Test",
            "short_description": "Draft knowledge should not be used for answering.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["draft_topic"],
            "query": "Explain orbit draft only knowledge",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "DISABLED-KNOWLEDGE-NOT-RETRIEVED-TEST",
            "test_title": "Disabled Knowledge Not Retrieved Test",
            "short_description": "Disabled knowledge should not be retrieved even if metadata matches.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["disabled_topic"],
            "query": "Explain orbit disabled only knowledge",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "MISSING-EMBEDDING-SAFETY-TEST",
            "test_title": "Missing Embedding Safety Test",
            "short_description": "Knowledge chunk without embedding should not crash retrieval.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["missing_embedding_topic"],
            "query": "Explain orbit missing embedding safety",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Orbit Analyst",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "QUERY-LOG-ALLOWED-TEST",
            "test_title": "Query Log Allowed Test",
            "short_description": "Allowed retrieval should complete successfully and be available for query logging.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["overview_topic"],
            "query": "What is Nexus Test Orbit?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Nexus Test Orbit",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "QUERY-LOG-FALLBACK-TEST",
            "test_title": "Query Log Fallback Test",
            "short_description": "No-context fallback should complete safely and be available for query logging.",
            "test_category": "Governance",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": SYNTHETIC["missing_topic"],
            "query": "Log this unknown synthetic fallback question",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        
                # ------------------------------------------------------------
        # INGESTION / INGESTED RETRIEVAL
        # ------------------------------------------------------------
        {
            "name": "INGESTED-PUBLIC-RETRIEVAL-TEST",
            "test_title": "Ingested Public Retrieval Test",
            "short_description": "Validates retrieval from ingestion-generated public knowledge chunks.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "public ingested hire return valuation governed knowledge retrieval",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Hire return valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "INGESTED-TENANT-ISOLATION-TEST",
            "test_title": "Ingested Tenant Isolation Test",
            "short_description": "Wrong tenant must not retrieve ingested knowledge.",
            "test_category": "Custom",
            "tenant": "TEST-NEXUS-ALT",
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "How does hire return valuation work?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "INGESTED-BUSINESS-UNIT-ISOLATION-TEST",
            "test_title": "Ingested Business Unit Isolation Test",
            "short_description": "Wrong Business Unit must not retrieve ingested knowledge.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["other_business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "How does hire return valuation work?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "INGESTED-ROLE-ALLOWED-TEST",
            "test_title": "Ingested Role Allowed Test",
            "short_description": "Allowed role should retrieve restricted ingested knowledge.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "Restricted ingested payroll valuation knowledge available only to Accounts Manager",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Restricted ingested payroll valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "INGESTED-ROLE-DENIED-TEST",
            "test_title": "Ingested Role Denied Test",
            "short_description": "Unauthorized role must not retrieve restricted ingested knowledge.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "restricted margin knowledge",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Sales User",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "INGESTED-KEYWORD-RETRIEVAL-TEST",
            "test_title": "Ingested Keyword Retrieval Test",
            "short_description": "Business keywords should retrieve ingestion-generated chunks.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",
            "query": "scaffold hire return inspection valuation",
            "top_k": 5,
            "use_case": "qa",            
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "scaffold hire return inspection",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "INGESTED-MISSING-EMBEDDING-SAFETY-TEST",
            "test_title": "Ingested Missing Embedding Safety Test",
            "short_description": "Retrieval must not crash when ingested chunk embedding is missing.",
            "test_category": "Custom",
            "tenant": SYNTHETIC["tenant"],
            "business_unit": SYNTHETIC["business_unit"],
            "context": SYNTHETIC["context"],
            "sub_context": SYNTHETIC["sub_context"],
            "entity_type": SYNTHETIC["entity_type"],
            "entity": SYNTHETIC["entity"],
            "topic": "Ingested Retrieval",            
            "query": "ingested missing embedding safety",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
    ]

    for row in test_cases:
        upsert_test_case(row)


def upsert_test_case(data):
    test_title = data.get("test_title")

    existing_name = frappe.db.get_value(
        "Nexus Test Case",
        {"test_title": test_title},
        "name",
    )

    if existing_name:
        if not UPDATE_EXISTING:
            print(f"Skipped existing test case: {existing_name}")
            return

        doc = frappe.get_doc("Nexus Test Case", existing_name)
        action = "Updated"
    else:
        doc = frappe.new_doc("Nexus Test Case")
        action = "Inserted"

    for key, value in data.items():
        if key != "name":
            doc.set(key, value)

    doc.enabled = 1

    if doc.is_new():
        doc.insert(ignore_permissions=True)
    else:
        doc.save(ignore_permissions=True)

    frappe.db.commit()

    print(f"{action}: {test_title}")