import frappe


UPDATE_EXISTING = True


def execute():
    test_cases = [
        {
            "name": "PUBLIC-OVERVIEW-TEST",
            "test_title": "Public Overview Test",
            "short_description": "Guest asks public DIGITZ ERP overview question.",
            "test_category": "Public Knowledge",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WEBSITE-PUBLIC-QA-TEST",
            "test_title": "Website Public Q&A Test",
            "short_description": "Website visitor asks a public DIGITZ ERP Q&A question.",
            "test_category": "Public Knowledge",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "Can you explain DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "caller_system": "Website Q&A",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WEBSITE-CHAT-PUBLIC-TEST",
            "test_title": "Website Chat Public Test",
            "short_description": "Website chatbot answers a public DIGITZ ERP question.",
            "test_category": "Response Behaviour",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "Hi, what is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "chat",
            "caller_system": "Website Chat",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "RESTRICTED-DENIAL-TEST",
            "test_title": "Restricted Access Denial Test",
            "short_description": "Sales User should not access restricted valuation knowledge.",
            "test_category": "Access Control",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Sales User",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "FINANCE-ALLOWED-TEST",
            "test_title": "Finance Allowed Test",
            "short_description": "Accounts Manager accesses restricted valuation knowledge.",
            "test_category": "Access Control",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Hire Return valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "PROJECT-WITH-GENERAL-TEST",
            "test_title": "Project + General Test",
            "short_description": "Project query allows project-specific knowledge and general fallback without leaking unrelated project knowledge.",
            "test_category": "Project Scope",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "with_general",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "STRICT-PROJECT-TEST",
            "test_title": "Strict Project Test",
            "short_description": "Project query retrieves only project-specific knowledge.",
            "test_category": "Project Scope",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "strict",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "OTHER-PROJECT-STRICT-LEAKAGE-TEST",
            "test_title": "Other Project Leakage - Strict",
            "short_description": "Strict project mode should not retrieve another project's knowledge.",
            "test_category": "Project Scope",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "XYZ Implementation",
            "project_scope_mode": "strict",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "NO-CONTEXT-FALLBACK-TEST",
            "test_title": "No Context Fallback Test",
            "short_description": "Unknown topic should trigger the safe fallback answer.",
            "test_category": "Fallback",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Missing Topic",
            "query": "Unknown question",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "WEBSITE-NO-CONTEXT-FALLBACK-TEST",
            "test_title": "Website No Context Fallback Test",
            "short_description": "Website visitor unknown question should return safe fallback.",
            "test_category": "Public Knowledge",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Missing Topic",
            "query": "Can you explain an unknown module?",
            "top_k": 5,
            "use_case": "qa",
            "caller_system": "Website Q&A",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "BUSINESS-UNIT-ISOLATION-TEST",
            "test_title": "Business Unit Isolation Test",
            "short_description": "Wrong Business Unit should not leak ERP Product knowledge.",
            "test_category": "Business Unit Scope",
            "tenant": "TEST-NEXUS",
            "business_unit": "Other Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "CHAT-RESPONSE-MODE-TEST",
            "test_title": "Chat Response Mode Test",
            "short_description": "Validates chatbot response behavior using approved knowledge.",
            "test_category": "Response Behaviour",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "chat",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "QA-RESPONSE-MODE-TEST",
            "test_title": "Q&A Response Mode Test",
            "short_description": "Validates formal Q&A response behavior using approved knowledge.",
            "test_category": "Response Behaviour",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "TOP-K-LIMIT-TEST",
            "test_title": "Top K Limit Test",
            "short_description": "Limits retrieval to one source when top_k is 1.",
            "test_category": "Response Behaviour",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 1,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "RETRIEVAL-STABILITY-SCORE-TEST",
            "test_title": "Retrieval Stability Score Test",
            "short_description": "Validates retrieval stability scoring visibility for grounded retrieval.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "Hire Return valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "STRICT-PROJECT-NO-GENERAL-LEAKAGE-TEST",
            "test_title": "Strict Project No General Leakage",
            "short_description": "Strict project mode must not retrieve general fallback chunks.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "strict",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WITH-GENERAL-PROJECT-BALANCE-TEST",
            "test_title": "With General Project Balance Test",
            "short_description": "Project with general mode should balance project and general retrieval safely.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "with_general",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation rules",
            "top_k": 10,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "RERANK-STABILITY-DEBUG-TEST",
            "test_title": "Rerank Stability Debug Test",
            "short_description": "Validates reranking and retrieval debug visibility.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return stock valuation handling",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },               
        {
            "name": "MULTI-QUERY-STABILITY-TEST",
            "test_title": "Multi Query Stability Test",
            "short_description": "Validates that multi-query retrieval consistently retrieves valuation knowledge for Hire Return.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "with_general",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "How is Hire Return valuation calculated?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "WEAK-RETRIEVAL-STABILITY-TEST",
            "test_title": "Weak Retrieval Stability Test",
            "short_description": "Validates that weak retrieval does not produce an unsafe answer when confidence is low.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "with_general",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Unrelated Topic",
            "query": "Explain something that is not available in the approved Nexus knowledge.",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "RESTRICTED-CHUNK-STABILITY-TEST",
            "test_title": "Restricted Chunk Stability Test",
            "short_description": "Restricted chunks must remain excluded during stable retrieval scoring.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Sales User",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "DENIED-CHUNK-NOT-SELECTED-TEST",
            "test_title": "Denied Chunk Not Selected Test",
            "short_description": "Validates that denied restricted chunks are not selected in final retrieval results.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Sales User",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "INGESTED-KNOWLEDGE-SOURCE-QA-TEST",
            "test_title": "Ingested Knowledge Source Q&A Test",
            "short_description": "Validates that manually ingested DIGITZ ERP overview knowledge can be retrieved and answered.",
            "test_category": "Governance",
            "tenant": "DIGITZ-ERP",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "Product Overview",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Platform Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "SOURCE-CITATION-CONTRACT-TEST",
            "test_title": "Source Citation Contract Test",
            "short_description": "Validates that answers from ingested knowledge return at least one source citation.",
            "test_category": "Governance",
            "tenant": "DIGITZ-ERP",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "Product Overview",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Platform Overview",
            "query": "Explain DIGITZ ERP overview",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "FORMATTED-ANSWER-QA-TEST",
            "test_title": "Formatted Answer Q&A Test",
            "short_description": "Validates that Q&A answer flow remains successful after formatted response support.",
            "test_category": "Response Behaviour",
            "tenant": "DIGITZ-ERP",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "Product Overview",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Platform Overview",
            "query": "What does DIGITZ ERP help businesses manage?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "accounting",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "SEMANTIC-CHUNKING-RETRIEVAL-TEST",
            "test_title": "Semantic Chunking Retrieval Test",
            "short_description": "Validates that paragraph-aware chunks remain retrievable for accounting overview content.",
            "test_category": "Governance",
            "tenant": "DIGITZ-ERP",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "Product Overview",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Platform Overview",
            "query": "What accounting processes are managed in DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "accounting",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
                {
            "name": "TENANT-ISOLATION-TEST",
            "test_title": "Tenant Isolation Test",
            "short_description": "TEST-NEXUS should not retrieve DIGITZ-ERP tenant knowledge.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "Product Overview",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Platform Overview",
            "query": "Explain DIGITZ ERP platform overview",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "DRAFT-KNOWLEDGE-NOT-RETRIEVED-TEST",
            "test_title": "Draft Knowledge Not Retrieved Test",
            "short_description": "Draft knowledge should not be used for answering.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Draft Topic",
            "query": "Explain draft only knowledge",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "DISABLED-KNOWLEDGE-NOT-RETRIEVED-TEST",
            "test_title": "Disabled Knowledge Not Retrieved Test",
            "short_description": "Disabled knowledge should not be retrieved even if metadata matches.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Disabled Topic",
            "query": "Explain disabled only knowledge",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "DENY-OVER-ALLOW-PRECEDENCE-TEST",
            "test_title": "Deny Over Allow Precedence Test",
            "short_description": "If a role is both allowed and denied, denial must win.",
            "test_category": "Access Control",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Deny Priority",
            "query": "Explain deny priority valuation rule",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "restricted",
            "expected_answer_contains": "You do not have permission",
            "expected_source_count_min": 0,
            "expected_fallback_used": 0,
        },
        {
            "name": "MULTI-ROLE-ALLOWED-TEST",
            "test_title": "Multi Role Allowed Test",
            "short_description": "User with multiple roles should access knowledge if one role is allowed.",
            "test_category": "Access Control",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "Hire Return valuation",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Sales User,Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "valuation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "PROJECT-PREFERRED-OVER-GENERAL-TEST",
            "test_title": "Project Preferred Over General Test",
            "short_description": "With general mode should still retrieve project-specific valuation knowledge.",
            "test_category": "Project Scope",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "project": "ABC Implementation",
            "project_scope_mode": "with_general",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Valuation",
            "query": "ABC Implementation Hire Return valuation rules",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "allowed",
            "expected_answer_contains": "ABC Implementation",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "QUERY-LOG-ALLOWED-TEST",
            "test_title": "Query Log Allowed Test",
            "short_description": "Allowed retrieval should complete successfully and be available for query logging.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Overview",
            "query": "What is DIGITZ ERP?",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "allowed",
            "expected_answer_contains": "DIGITZ ERP",
            "expected_source_count_min": 1,
            "expected_fallback_used": 0,
        },
        {
            "name": "QUERY-LOG-FALLBACK-TEST",
            "test_title": "Query Log Fallback Test",
            "short_description": "No-context fallback should complete safely and be available for query logging.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Missing Topic",
            "query": "Log this unknown fallback question",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Guest",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
        {
            "name": "MISSING-EMBEDDING-SAFETY-TEST",
            "test_title": "Missing Embedding Safety Test",
            "short_description": "Knowledge chunk without embedding should not crash retrieval.",
            "test_category": "Governance",
            "tenant": "TEST-NEXUS",
            "business_unit": "ERP Product",
            "context": "ERP",
            "sub_context": "General",
            "entity_type": "Product",
            "entity": "DIGITZ ERP",
            "topic": "Missing Embedding",
            "query": "Explain missing embedding safety",
            "top_k": 5,
            "use_case": "qa",
            "user_roles": "Accounts Manager",
            "expected_access_status": "no_context",
            "expected_answer_contains": "I do not have enough approved knowledge",
            "expected_source_count_min": 0,
            "expected_fallback_used": 1,
        },
    ]

    for row in test_cases:
        upsert_test_case(row)


def upsert_test_case(data):
    test_title = data.get("test_title")

    existing_name = frappe.db.get_value(
        "Nexus Test Case",
        {"test_title": test_title},
        "name",
    )

    if existing_name:
        if not UPDATE_EXISTING:
            print(f"Skipped existing test case: {existing_name}")
            return

        doc = frappe.get_doc("Nexus Test Case", existing_name)
        action = "Updated"
    else:
        doc = frappe.new_doc("Nexus Test Case")
        action = "Inserted"

    for key, value in data.items():
        if key != "name":
            doc.set(key, value)

    doc.enabled = 1

    if doc.is_new():
        doc.insert(ignore_permissions=True)
    else:
        doc.save(ignore_permissions=True)

    frappe.db.commit()

    print(f"{action}: {test_title}")